### ISSUE TITLE
Move GeoResolverInitializer.getInstance().getLocationResolver() to init method

### ISSUE THREAD

**Issue by thanujalk** [wso2/analytics-is#349]
**Description:**

Move GeoResolverInitializer.getInstance().getLocationResolver() to init method in following Functiom executers.
- https://github.com/wso2/analytics-is/blob/master/components/org.wso2.analytics.is/src/main/java/org/wso2/analytics/is/siddhi/extension/IpToCityExtension.java
- https://github.com/wso2/analytics-is/blob/master/components/org.wso2.analytics.is/src/main/java/org/wso2/analytics/is/siddhi/extension/IpToCountryExtension.java

**Comment by Avarjana** [comment]
Closing since this repository is no longer maintained. Analytics IS was replaced by ELK analytics with https://github.com/wso2-extensions/identity-elk-integration.
