### ISSUE TITLE
Error while processing spark script in Geo UDF for records with remoteIp has "unknown" as value.

### ISSUE THREAD

**Issue by ksdperera** [wso2/analytics-is#362]
**Description:**
As per the current findings, we found the two issues:

1. Spark Geo Location UDF cannot handle the disputed records("unknown" as remoteIp value),  Ideally whatever the values that are published from the IS side, UDF should handle them. If we fix the UDF, this malformed records will not be an issue and purging task will remove this disputed records accordingly.

2. The IS analytics statistics publisher published  'unknown' as value for the remoteIp attribute.

**Suggested Labels:**
is-analytics, 5.2.0

**Affected Product Version:**
IS Analytics 5.2.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
UDF Issue: this can be reproduced if we simulate and send the value "unknown" to the stream ORG_WSO2_IS_ANALYTICS_STREAM_OVERALLAUTHENTICATION and run the IsAnalytics-SparkScript-AuthenticationData script which has the method "getCountry"

IS Publisher Issue: 
We had tried to reproduce this, but couldn't figure the root cause of the issue.

**Comment by GDRDABARERA** [comment]
This is fixed with https://github.com/wso2/shared-analytics/pull/155

**Comment by ruwanta** [comment]
Updated shared-analytics 1.0.4 in IS which has the fix.
