### ISSUE TITLE
Error in storing region extracted from the remote IP

### ISSUE THREAD

**Issue by pamodaaw** [wso2/analytics-is#364]
**Description:**
In the execution plan, "IsAnalytics-ExecutionPlan-AuthenticationData", the region is extracted from the IP using the siddhi function **isAnalytics:ipToCountry(remoteIp)**. This function returns an object and it is directly stored in the event table. then the region column contains the reference to that object.

**Affected Product Version:** 
IS-Analytics 5.5.0-Alpha

**Comment by emswbandara** [comment]
Fixed with https://github.com/wso2/analytics-is/pull/365
