### ISSUE TITLE
Some streams which capture PII information are missed out from streams.json file

### ISSUE THREAD

**Issue by dilinisg** [wso2/analytics-is#396]
**Description:**
There are only 3 streams available by default in the streams.json. But, there are some other streams which also capture PII data such as username, remote IP, localUsername etc. which are not configured in the streams.json by default in the forgetme tool. 

For example:

 - org.wso2.is.analytics.stream.AuthStatPerMinute:1.0.0		
 - org.wso2.is.analytics.stream.IdpAuthStatPerMinute:1.0.0		
 - org.wso2.is.analytics.stream.LocalUserAuthStatPerMinute:1.0.0
 - org.wso2.is.analytics.stream.LoginSuccessAfterMultipleFailures:1.0.0		
 - org.wso2.is.analytics.stream.OverallSession:1.0.0		
 - org.wso2.is.analytics.stream.ProcessedOverallAuthentication:1.0.0		
 - org.wso2.is.analytics.stream.RoleAuthStatPerMinute:1.0.0		
 - org.wso2.is.analytics.stream.SessionInfo:1.0.0			
 - org.wso2.is.analytics.stream.UserAuthStatPerMinute:1.0.0		
 - org.wso2.is.analytics.stream.UserRegionStatPerMinute:1.0.0		

**Expected**
All the streams which capture PII data should be available in the streams.json by default, so that the users do not need to worry about configuring the streams.json.

**Suggested Labels:**
Bug
Priority - High, 
Severity - Major,

**Affected Product Version:**
IS 5.5.0 RC2

**Comment by Avarjana** [comment]
Closing since this repository is no longer maintained. Analytics IS was replaced by ELK analytics with https://github.com/wso2-extensions/identity-elk-integration.
