### ISSUE TITLE
[IS] [Analytics] The geo location script needs to be updated and stored in a generic location

### ISSUE THREAD

**Issue by YvonneW** [wso2/analytics-is#451]
**Description:**
The following should be added to the _Geolocation Data/dbscripts/mysql.sql_ script.
`CREATE DATABASE GEO_LOCATION_DATA;
USE GEO_LOCATION_DATA;`

This file is currently stored in a personal SVN location. Shall we store it in a standard location? 

**Suggested Labels:**
TBD

**Suggested Assignees:**
@dilin993 

**Affected Product Version:**
5.7 RC3

**OS, DB, other environment details and versions:**    
TBD

**Steps to reproduce:**
https://docs.wso2.com/display/IS570/Using+Geolocation+Based+Statistics

**Related Issues:**
TBD

**Comment by Avarjana** [comment]
Closing since this repository is no longer maintained. Analytics IS was replaced by ELK analytics with https://github.com/wso2-extensions/identity-elk-integration.
