### ISSUE TITLE
Date picker resets when navigating to different page

### ISSUE THREAD

**Issue by ruwanta** [wso2/analytics-is#486]
**Description:**
Analytics dashboard (Stream Processor based) resets the selected date time when navigating to different page.
This causes usability issue, where user has to always re-enter the interested date range.

Can be fixed with remembering the current selected date in "local storage" or somewhere within the browser, or the URL.

**Related Issues:**
https://wso2.org/jira/browse/ANLYIS-174

**Comment by Avarjana** [comment]
Closing since this repository is no longer maintained. Analytics IS was replaced by ELK analytics with https://github.com/wso2-extensions/identity-elk-integration.
