### ISSUE TITLE
Better to use proper names for lables/names instead of method names in Graphs

### ISSUE THREAD

**Issue by ruwanta** [wso2/analytics-is#487]
**Description:**
Better to use proper names for lables/names instead of method names in Graphs

It's better have readable names instead of method names for labels and other naming conventions in graphs. For an example, when hover the graph points in "Overall" login attempts, it displayed the value names as authActionCount, timeStamp and authActionType. (check attachments )

More info can be found in the JIra
https://wso2.org/jira/browse/ANLYIS-152

**Related Issues:**
https://wso2.org/jira/browse/ANLYIS-152

**Comment by Avarjana** [comment]
Closing since this repository is no longer maintained. Analytics IS was replaced by ELK analytics with https://github.com/wso2-extensions/identity-elk-integration.
