### ISSUE TITLE
Show tenant domain in the username label in all gadgets

### ISSUE THREAD

**Issue by ruwanta** [wso2/analytics-is#488]
**Description:**
User name is shown without tenant domain in some charts.
It is difficult to distinguish the user as each tenant would have same local name as user name.
We need to suffix the tenant domain for each username label. 

**Related Issues:**
https://wso2.org/jira/browse/ANLYIS-156

**Comment by Avarjana** [comment]
Closing since this repository is no longer maintained. Analytics IS was replaced by ELK analytics with https://github.com/wso2-extensions/identity-elk-integration.
