### ISSUE TITLE
Widgets failing load and issue with re-logging in Dashboard

### ISSUE THREAD

**Issue by sybernix** [wso2/analytics-is#493]
**Description:**
Issue 1: Widgets failing load due to error 'Failed to execute 'send' on 'WebSocket': Still in CONNECTING state'

When logged into the IS Analytics Dashboard and refreshed, some widgets fail to load intermittently. 

While giving out the error "Failed to execute 'send' on 'WebSocket': Still in CONNECTING state" in the browser console. 

Issue 2: Redirect to /portal/undefined when login after a logout in IS Analytics 5.7.0 Dashboard.

When logged into the  IS Analytics Dashboard after a logout, gets re-directed to /portal/undefined.

How to reproduce.

Login to the dashboard
Log out from the dashboard
Log in again to the dashboard and it goes to the following page with /undefined

**Affected Product Version:**
5.8.0

**Comment by Avarjana** [comment]
Closing since this repository is no longer maintained. Analytics IS was replaced by ELK analytics with https://github.com/wso2-extensions/identity-elk-integration.
