### ISSUE TITLE
Getting Negative Values as the FailureCount

### ISSUE THREAD

**Issue by Methma** [wso2/analytics-is#496]
**Description:**
Getting a negative value for the local login attempts graph in IS-Analytics. The queries in the network call is calculating the failure count for this widget is as follows.

`*sum(authFailureCount * -1) *as FailureCount`

**Suggested Labels:**
is-analytics

**Affected Product Version:**
5.7.0
5.8.0

**Steps to reproduce:**
1. Configure IS Analytics 5.7.0 or 5.8.0.
2. Try to logging to the dashboard portal with wrong user names and passwords.
3. Check the Local login Attempts graph.

**Comment by Avarjana** [comment]
Closing since this repository is no longer maintained. Analytics IS was replaced by ELK analytics with https://github.com/wso2-extensions/identity-elk-integration.
