### ISSUE TITLE
Cannot use dashboard with PostgreSQL

### ISSUE THREAD

**Issue by yuniet87** [wso2/analytics-is#497]
**Description:**
When configuring Postgresql for the IS analytics DB specifically the section WSO2_DASHBOARD_DB, it shows the following error on startup:
Caused by: java.sql.SQLFeatureNotSupportedException: Method org.postgresql.jdbc.PgConnection.createBlob () is not yet implemented

**Affected Product Version:**
wso2is-analytic-dashboard: 5.8.0

**OS, DB, other environment details and versions:** 
PostgreSQL: 12.2
Postgres JDBC driver version: 42.2.12

**Steps to reproduce:**
Open the file <IS_ANALYTICS_HOME>/conf/dashboard/deployment.yaml. Search WSO2_DASHBOARD_DB section and modify:
* jdbcUrl: 'jdbc:postgresql://localhost:5432/WSO2IS_DASHBOARD_DB'
* driverClassName: org.postgresql.Driver

**Comment by Avarjana** [comment]
Closing since this repository is no longer maintained. Analytics IS was replaced by ELK analytics with https://github.com/wso2-extensions/identity-elk-integration.
